### ISSUE TITLE
hwinfo mapping: hd_t

### ISSUE THREAD

**Issue by brianmcgee** [numtide/nixos-facter#61]
Partial mapping.

https://github.com/openSUSE/hwinfo/blob/c87f449f1d4882c71b0a1e6dc80638224a5baeed/src/hd/hd.h#L2203-L2605

## TODO
- [ ] Status
- [ ] Config string
- [ ] Hotplug
- [ ] Hotplug_slot
- [ ] is (item specific statuses)
- [ ] HAL property list
- [ ] Persistent property list
